### ISSUE TITLE
Should we allow bonus points?

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/remarks#11]
I had this feature in my shell-scripted format. The idea was that the syntax was slightly different for "bonus judgements":

```
# Theory: /50
## Question 1: 5/10
## Question 2: 5/20
## Question 3: 5/20
## Bonus: +5
```

The template would then be

```
## Bonus: +0
```

Bonus points should be accounted separately to keep the overflow counts as they are, and to make bonus points selectively applicable (i.e., only if need be).

**Comment by oleks** [comment]
@kirkedal What do you think?

**Comment by kirkedal** [comment]
I find it a good idea.

When making the grading sheets for CompSys, I was thinking of taking out
some points for a final distribution. I have previously found that I
sometimes adjust some random points i make take it to the level that I find
reasonable. Having a way to make this adjustment clear and be able to add a
reason, would be great.

**Comment by oleks** [comment]
Done, except that bonus points are not accounted for separately, but just contribute to an overall sum. Incidentally, computed sums may exceed the maximum by design.
