### ISSUE TITLE
Compare to template

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/remarks#13]
Sometimes, you want to extend the template mid-way during grading. For instance, you discover an important structural comment missing from the original template. Some tool support for this would be nice. For instance,

* Check if a judgement "conforms" to a template judgement.
* Add missing comments with TODO markers.

**Comment by kirkedal** [comment]
I think that it would be useful to have a template definition. This can be useful in `validate` and the different exporting. 

However, If we are to use it to update the files, we need to make the parser remember the file structure. This could also be useful for making a listing of what is missing to be done and return the file to be updated. 
Perhaps we can have the option to leave the points in the leaves blank as an indication of "to be done".

**Comment by oleks** [comment]
This is now #33 .
