### ISSUE TITLE
We don't need both check and show

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/remarks#14]
`remarks check` and `remarks show` will likely show the same pretty-printing in the end (currently, `remarks show` doesn't perform a `validate`, but it probably should.

@kirkedal

**Comment by kirkedal** [comment]
I would still keep both, but change them

* ´remarks check´ runs ´validate´ and prints "everything fine" if validate
does not check. After you update some files, I find it would be useful to
have a sanity check
* ´remarks show´ runs ´validate´ and shows the content
