### ISSUE TITLE
Empty points in Assignment-leaves to indicate pending corrections

### ISSUE THREAD

**Issue by kirkedal** [DIKU-EDU/remarks#16]
@oleks comments?

Getting a list of which correction are missing could give a good overview. I could have used it for the Assignments

**Comment by oleks** [comment]
Yes, that was actually intended. It's just that #10 hasn't been resolved yet.

**Comment by kirkedal** [comment]
I might not be an error in the check, but could be treated as 0. Then have
another command `remarks pending` that would print a ascii tree structure
of the pending corrections.

**Comment by oleks** [comment]
On Thu, Jan 19, 2017 at 10:47 AM, Michael Kirkedal Thomsen <
notifications@github.com> wrote:

> I might not be an error in the check, but could be treated as 0. Then have
> another command `remarks pending` that would print a ascii tree structure
> of the pending corrections.
>

I like `remarks pending`.

**Comment by kirkedal** [comment]
The implementation is build on Data.Tree, which results in large trees. Perhaps make an new implementation of show tree that is more compact.

**Comment by kirkedal** [comment]
@oleks can you have a look if the new pending-trees also looks nice on Linux. If not I'll update to a more basic char-set.

**Comment by oleks** [comment]
On Thu, Jan 19, 2017 at 6:36 PM, Michael Kirkedal Thomsen <
notifications@github.com> wrote:

> @oleks <https://github.com/oleks> can you have a look if the new
> pending-trees also looks nice on Linux. If not I'll update to a more basic
> char-set.
>
It looks great in rxvt-unicode-256color, Konsole, and xterm! Beware
however, in principle, remarks is cross-platform. Someone(tm) should test
this on Windows.

**Comment by kirkedal** [comment]
Yes, that was also why I asked you. Perhaps just revert to the basic
character set

**Comment by kirkedal** [comment]
* 030380674c38871623eb70f0180aec62e3b7e6eb
* e8ce101ee0129df5de882d9b77779aaa7802c468
* b01af1be5f8e3d5fa7f2b69f695aaefca84b8742
