### ISSUE TITLE
Automate summation / quickfix bad sums

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/remarks#2]
Teaching assistants shouldn't be asked to sum things up correctly. It should be easy to sum up points starting from the bottom-most judgements.

**Comment by oleks** [comment]
There is now a plan for this, and it requires #5 .

**Comment by oleks** [comment]
To this end, I added a unification procedure: ce5e6576676848722c86e01458c2e2730dd7ab94

**Comment by kirkedal** [comment]
I have added a sum function to the properties, what sums values of a given propertyName in sub-judgements. Syntax is `sum([propertyName]`. PropertyInterp it adds `  :Total: sum(Total)`and `  :MaxPoints: sum(MaxPoints)` to all judgements. These sums are used for exportation. 

If you define other fields, you can also take sum of them. It only sums from the sub-judgements where the propertyName exist; all other are treated as 0.

I don't know if this was what you were searching for.

**Comment by oleks** [comment]
I think so.
