### ISSUE TITLE
Add a properties syntax

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/remarks#6]
Some essential properties: student name, id, and grade.
It would be nice to extract just these properties into a CSV format.

Perhaps the format should be [similar to org-mode](http://orgmode.org/manual/Property-syntax.html#Property-syntax):

```
# Total: 45/100
  :Name: Donald E. Knuth
  :Grade: 00
## Theory: 40/50
  + Excellent.
  - But you need a CS degree to understand what's going on.
## Practice: 5/50
  + There is an implementation.
  - Only proven correct, but not tested.
```

I think properties should be global.

The CSV export command syntax could then look something like this:

```
$ remarks export --format "Name;Grade;Total;Theory;Practice" <path>
```

This is a prerequisite for #3.

**Comment by oleks** [comment]
@kirkedal Any objections to the format I suggest above?

**Comment by kirkedal** [comment]
No objections. I will look at it a bit later.

**Comment by athas** [comment]
Can the value of a property contain newlines?

**Comment by oleks** [comment]
On Tue, Jan 17, 2017 at 11:41 PM, Troels Henriksen <notifications@github.com
> wrote:

> Can the value of a property contain newlines?
>
I don't think we should allow that. That would encourage complicated
properties, and it wouldn't be very collector-friendly.

**Comment by kirkedal** [comment]
I am thinking of forcing properties to the topmost judgement only. So basically this means that I will change the parser to return an IO [Assignment ([Property], Judgement)] in IO [Judgement].

**Comment by oleks** [comment]
On Wed, Jan 18, 2017 at 11:22 AM, Michael Kirkedal Thomsen
<notifications@github.com> wrote:
> I am thinking of forcing properties to the topmost judgement only. So basically this means that I will change the parser to return an IO [Assignment ([Property], Judgement)] in IO [Judgement].

I think this would make things more complicated. The parser is
intentionally less specific than this. This makes it possible to let
`parseFileInDir` and `parsePath` be mutually recursive.

Checking that only "top-level" judgements have properties can be done
in [app/Main.hs](app/Main.hs).

-- 
Oleks

**Comment by oleks** [comment]
I also think it could be a useful feature if TA's could fill in certain properties (deep down in their own files).

**Comment by kirkedal** [comment]
You were right about this. Parser done! New thought! 

The proposed export format mixes titles and total points from different levels. That can quickly get out of hand. Should it be a depth or breath first search. Also I would like to use more wordy name for titles. Instead I propose the following. 
All Assignments (that includes leaf-assignments) have 3 predefines properties: Title, Total and MaxPoints. These comes from the header. 
When defining a property, we can then refer and read values from to the properties of the leaves. The format here is assuming that they are ordered and thus refers to the numbering in the list. An example could then be:

```
# Total: 45/100
  :Name: Donald E. Knuth
  :Grade: 00
  :Theory: [1.Total]
  :Practice: [2.Total]
## Theory sharpens the brain: 40/50
  + Excellent.
  - But you need a CS degree to understand what's going on.
## Practice your skills: 5/50
  + There is an implementation.
  - Only proven correct, but not tested.
```
Then the export command will be uniquely defined.
`$ remarks export --format "Name;Grade;Total;Theory;Practice" <path>`

I don't like the format for referencing to leaves, but I lack something much better.

This can even be extended to a small scripting language, that can calculate grades and similar. We can even move the calculation of Total and MaxPoints to have a predefined summation of the leaves.

**Comment by oleks** [comment]
On Wed, Jan 18, 2017 at 1:25 PM, Michael Kirkedal Thomsen <
notifications@github.com> wrote:

> You were right about this. Parser done! New thought!
>
> The proposed export format mixes titles and total points from different
> levels. That can quickly get out of hand. Should it be a depth or breath
> first search. Also I would like to use more wordy name for titles. Instead
> I propose the following.
> All Assignments (that includes leaf-assignments) have 3 predefines
> properties: Title, Total and MaxPoints. These comes from the header.
> When defining a property, we can then refer and read values from to the
> properties of the leaves. The format here is assuming that they are ordered
> and thus refers to the numbering in the list. An example could then be:
>
> # Total: 45/100
>   :Name: Donald E. Knuth
>   :Grade: 00
>   :Theory: [1.Total]
>   :Practice: [2.Total]
> ## Theory sharpens the brain: 40/50
>   + Excellent.
>   - But you need a CS degree to understand what's going on.
> ## Practice your skills: 5/50
>   + There is an implementation.
>   - Only proven correct, but not tested.
>
> I like this! I also like "total" in stead of "points"; perhaps you could
refactor this throughout as well? Else it seems that I like refactoring :-)

> This can even be extended to a small scripting language, that can
> calculate grades and similar. We can even move the calculation of Total and
> MaxPoints to have a predefined summation of the leaves.
>
Yes, that would be nice too.

 --
Oleks

**Comment by kirkedal** [comment]
* 50e19c6268ee8e4d3b5c6252f6bd6a492c18f071
* 15fb4ac2e33df189c16634da555fa4791666876d
* a36beceb6dbb7b5953372b018416a21070a574e2
