### ISSUE TITLE
Change # to *?

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/remarks#8]
Currently, judgements look like this:

```
# Theory: 0/50
## Question 1: 0/10
## Question 2: 0/20
## Question 3: 0/20
```

One suggestion is to change this to

```
* Theory: 0/50
** Question 1: 0/10
** Question 2: 0/20
** Question 3: 0/20
```

This would make remarks slightly more compatible with org-mode, making it slightly more wieldy for emacs users. However, `.mrk` files should be small, so folding/unfolding isn't expected to be in too great a demand.

The reason headers are written with `#` is to make files easy to `grep`. They are still easy to `grep` if we use `*` instead of `#`, since neutral comments must always be indented at least once.

**Comment by athas** [comment]
Yes, switch to `*`.  `#` makes me think of comments, not markup.

**Comment by kirkedal** [comment]
I tried to update a "real" file that is to be used for grading and using `*` for both headings and neutral item elements is confusing to look at. Too many stars. We should also change neutral elements then.

**Comment by kirkedal** [comment]
And `#` is used for titles in markdown

**Comment by oleks** [comment]
Let's close this for now.
